#!/bin/bash
jupyter serverextension enable --py nbserverproxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @jupyterlab/hub-extension@0.12 \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension

# install google cloud storage tools
# once gsutil is python 3 compatible we can remove this and install
# 'google-cloud-sdk' from conda-forge instead
# first, check if we have a gsutil command already
command -v gsutil
if [ $? -ne 0 ]; then
    curl https://sdk.cloud.google.com -o google_cloud.sh
    bash google_cloud.sh --disable-prompts
fi

#EOF
