#!/bin/bash
jupyter serverextension enable --py nbserverproxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @jupyterlab/hub-extension@0.12 \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension

# install google cloud storage tools
# once gsutil is python 3 compatible we can remove this and install
# 'google-cloud-sdk' from conda-forge instead
# first, check if we have a gsutil command already
command -v gsutil
if [ $? -ne 0 ]; then
    curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-236.0.0-linux-x86_64.tar.gz -o gc_sdk.tar.gz
    tar -xzf gc_sdk.tar.gz
    ./google-cloud-sdk/install.sh --usage-reporting false --path-update true --quiet
    source .bashrc
fi

#gcloud components update

#EOF
